Update to latest versions
buildertrend/eslint-plugin-enterprise-extras pull request #20
Opened 2024-06-27 20:51 UTC by dteske25

Bumps several packages to their latest versions
There were only minor edits to the tests due to changes in how the RuleTester was packaged

2024-07-01 21:54 UTC, C-Hess commented on package.json
> +  "version": "8.0.2",
This is considered a major change given the potentials to break builds

2024-07-01 22:00 UTC, C-Hess requested changes

2024-07-01 22:00 UTC, C-Hess commented on package.json
> +    "eslint": ">=7"
Shouldn't use >=7. If we're using version 8 to build, we probably shouldn't set the minimum version as a peer dependency to 7 unless we know there are no runtime issues with eslint 7 (which may be the case, I'm not sure). In addition, major changes of ESLint are likely to break compatibility with this library. It's best to continue to used fixed versions.

Assuming you know if v7 still works, this should probably be `7^ || 8^`

2024-07-02 16:51 UTC, daryl0313 approved these changes
LGTM

2024-07-02 18:34 UTC, C-Hess approved these changes

2024-07-02 18:34 UTC, merged